# Emscripten CMake toolchain for LMMS WebAssembly build
# Requires Qt 5 built for WebAssembly

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(CMAKE_C_COMPILER emcc)
set(CMAKE_CXX_COMPILER em++)
set(CMAKE_AR emar)
set(CMAKE_RANLIB emranlib)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -s ALLOW_MEMORY_GROWTH=1")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -s ALLOW_MEMORY_GROWTH=1")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -s ALLOW_MEMORY_GROWTH=1 -s WASM=1")

# Qt5 WASM installation path
set(QT5_WASM_PREFIX "/workspace/project/lmms-wasm-full/qt5-wasm")
set(Qt5_DIR "${QT5_WASM_PREFIX}/lib/cmake/Qt5")
set(Qt5Core_DIR "${QT5_WASM_PREFIX}/lib/cmake/Qt5Core")
set(Qt5Gui_DIR "${QT5_WASM_PREFIX}/lib/cmake/Qt5Gui")
set(Qt5Widgets_DIR "${QT5_WASM_PREFIX}/lib/cmake/Qt5Widgets")
set(Qt5Xml_DIR "${QT5_WASM_PREFIX}/lib/cmake/Qt5Xml")

# Disable features not available on WASM
set(WANT_ALSA OFF CACHE BOOL "" FORCE)
set(WANT_JACK OFF CACHE BOOL "" FORCE)
set(WANT_OSS OFF CACHE BOOL "" FORCE)
set(WANT_PULSEAUDIO OFF CACHE BOOL "" FORCE)
set(WANT_PORTAUDIO OFF CACHE BOOL "" FORCE)
set(WANT_SDL OFF CACHE BOOL "" FORCE)
set(WANT_SOUNDIO OFF CACHE BOOL "" FORCE)
set(WANT_SNDIO OFF CACHE BOOL "" FORCE)
set(WANT_VST OFF CACHE BOOL "" FORCE)
set(WANT_LV2 OFF CACHE BOOL "" FORCE)
set(WANT_LADSPA OFF CACHE BOOL "" FORCE)
set(WANT_CARLA OFF CACHE BOOL "" FORCE)
set(WANT_MP3LAME OFF CACHE BOOL "" FORCE)
set(WANT_OGGVORBIS OFF CACHE BOOL "" FORCE)
set(WANT_FLAC OFF CACHE BOOL "" FORCE)
set(WANT_STK OFF CACHE BOOL "" FORCE)
set(WANT_CALF OFF CACHE BOOL "" FORCE)
set(WANT_CAPS OFF CACHE BOOL "" FORCE)
set(WANT_CMT OFF CACHE BOOL "" FORCE)
set(WANT_TAP OFF CACHE BOOL "" FORCE)
set(WANT_SWH OFF CACHE BOOL "" FORCE)
set(WANT_VST_NOWINE OFF CACHE BOOL "" FORCE)
set(WANT_GIG OFF CACHE BOOL "" FORCE)
set(WANT_SF2 OFF CACHE BOOL "" FORCE)
set(WANT_SF3 OFF CACHE BOOL "" FORCE)
set(WANT_REMOTE OFF CACHE BOOL "" FORCE)
set(WANT_WERROR OFF CACHE BOOL "" FORCE)

# Enable WASM-specific features
set(LMMS_HAVE_WEB_AUDIO ON CACHE BOOL "" FORCE)

# Use static Qt
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
